### PR TITLE
Fixed compatibility with cocoapods 1.0.1

### PR DESCRIPTION
**Pull request by belkevich**
Changes:
* Removed UIKit (there any UI* class use)
* Updated podspec to 0.1.13

Please, merge this pull request. And don't forget to add tag `v0.1.13` and push podspec

### CODE REVIEW

**Comment by tkach** [comment]
+1 Merge please

**Comment by kondrashov** [comment]
+1

**Comment by belkevich** [comment]
Please, push new version to the cocoapods!
```bash
git tag -a v0.1.13 -m ""
git push origin --tags
pod trunk push Smartling.i18n.podspec
```

**Comment by kondrashov** [comment]
+1

**Comment by foo4u** [comment]
@belkevich @kondrashov CocoaPods update coming shortly.

**Comment by emilienh** [comment]
Update pushed

**Pull request merged**
